In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install datetime

Requirement already satisfied: datetime in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (5.5)
Requirement already satisfied: zope.interface in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from datetime) (7.2)
Requirement already satisfied: pytz in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from datetime) (2025.2)
Requirement already satisfied: setuptools in c:\users\sakib\appdata\local\programs\python\python313\lib\site-packages (from zope.interface->datetime) (80.9.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
from datetime import datetime

In [5]:
# Load the dataset
df = pd.read_csv("uncleaned_dataset (1).csv")

In [7]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,twenty,NaN,90576,2020-02-16,NaN,NaN,USA,NaN
1,David,NaN,NaN,64288,2018-02-21,NaN,NaN,Canada,NaN
2,Bob,twenty,NaN,39551,2019-04-17,NaN,NaN,NaN,NaN
3,Charlie,twenty,Female,unknown,2021-04-08,NaN,NaN,India,Bad
4,Alice,-5,NaN,unknown,2023-09-18,NaN,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37,F,35850,invalid_date,NaN,NaN,USA,Good
96,David,twenty,m,98631,2020-12-15,Y,user26@mail.com,UK,Average
97,Bob,-5,F,unknown,2023-05-18,Y,user14@mail.com,Canada,NaN
98,Eva,NaN,m,NaN,2021-11-05,NaN,user45@mail.com,UK,Good
99,Eva,57,F,80658,NaN,0,NaN,India,Average

In [8]:
# Name cleanup
df = df.dropna(subset=['Name'])

In [9]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,twenty,NaN,90576,2020-02-16,NaN,NaN,USA,NaN
1,David,NaN,NaN,64288,2018-02-21,NaN,NaN,Canada,NaN
2,Bob,twenty,NaN,39551,2019-04-17,NaN,NaN,NaN,NaN
3,Charlie,twenty,Female,unknown,2021-04-08,NaN,NaN,India,Bad
4,Alice,-5,NaN,unknown,2023-09-18,NaN,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37,F,35850,invalid_date,NaN,NaN,USA,Good
96,David,twenty,m,98631,2020-12-15,Y,user26@mail.com,UK,Average
97,Bob,-5,F,unknown,2023-05-18,Y,user14@mail.com,Canada,NaN
98,Eva,NaN,m,NaN,2021-11-05,NaN,user45@mail.com,UK,Good
99,Eva,57,F,80658,NaN,0,NaN,India,Average

In [12]:
# 1. Clean Age column
df['Age'] = pd.to_numeric(df['Age'], errors='coerce') 
df.loc[df['Age'] < 0, 'Age'] = np.nan
df['Age'] = df['Age'].fillna(df['Age'].median())

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\3454338088.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\3454338088.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(df['Age'].median())

In [13]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,NaN,90576,2020-02-16,NaN,NaN,USA,NaN
1,David,20.0,NaN,64288,2018-02-21,NaN,NaN,Canada,NaN
2,Bob,20.0,NaN,39551,2019-04-17,NaN,NaN,NaN,NaN
3,Charlie,20.0,Female,unknown,2021-04-08,NaN,NaN,India,Bad
4,Alice,20.0,NaN,unknown,2023-09-18,NaN,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,F,35850,invalid_date,NaN,NaN,USA,Good
96,David,20.0,m,98631,2020-12-15,Y,user26@mail.com,UK,Average
97,Bob,20.0,F,unknown,2023-05-18,Y,user14@mail.com,Canada,NaN
98,Eva,20.0,m,NaN,2021-11-05,NaN,user45@mail.com,UK,Good
99,Eva,57.0,F,80658,NaN,0,NaN,India,Average

In [14]:
# 2. Standardize Gender
df['Gender'] = df['Gender'].str.strip().str.capitalize()
df['Gender'] = df['Gender'].replace({'M': 'Male', 'F': 'Female'})
df['Gender'] = df['Gender'].fillna('Unknown')

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1326560358.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].str.strip().str.capitalize()
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1326560358.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].replace({'M': 'Male', 'F': 'Female'})
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1326560358.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].fillna('Unknown')

In [15]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576,2020-02-16,NaN,NaN,USA,NaN
1,David,20.0,Unknown,64288,2018-02-21,NaN,NaN,Canada,NaN
2,Bob,20.0,Unknown,39551,2019-04-17,NaN,NaN,NaN,NaN
3,Charlie,20.0,Female,unknown,2021-04-08,NaN,NaN,India,Bad
4,Alice,20.0,Unknown,unknown,2023-09-18,NaN,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850,invalid_date,NaN,NaN,USA,Good
96,David,20.0,Male,98631,2020-12-15,Y,user26@mail.com,UK,Average
97,Bob,20.0,Female,unknown,2023-05-18,Y,user14@mail.com,Canada,NaN
98,Eva,20.0,Male,NaN,2021-11-05,NaN,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658,NaN,0,NaN,India,Average

In [16]:
# 3. Clean Income
df['Income'] = pd.to_numeric(df['Income'], errors='coerce')
df.loc[df['Income'] < 0, 'Income'] = np.nan
df['Income'] = df['Income'].fillna(df['Income'].median())

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1021854766.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income'] = pd.to_numeric(df['Income'], errors='coerce')
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1021854766.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income'] = df['Income'].fillna(df['Income'].median())

In [17]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576.0,2020-02-16,NaN,NaN,USA,NaN
1,David,20.0,Unknown,64288.0,2018-02-21,NaN,NaN,Canada,NaN
2,Bob,20.0,Unknown,39551.0,2019-04-17,NaN,NaN,NaN,NaN
3,Charlie,20.0,Female,57072.0,2021-04-08,NaN,NaN,India,Bad
4,Alice,20.0,Unknown,57072.0,2023-09-18,NaN,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850.0,invalid_date,NaN,NaN,USA,Good
96,David,20.0,Male,98631.0,2020-12-15,Y,user26@mail.com,UK,Average
97,Bob,20.0,Female,57072.0,2023-05-18,Y,user14@mail.com,Canada,NaN
98,Eva,20.0,Male,57072.0,2021-11-05,NaN,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658.0,NaN,0,NaN,India,Average

In [18]:
# 4. Fix JoinDate
df['JoinDate'] = pd.to_datetime(df['JoinDate'], errors='coerce')
df['JoinDate'] = df['JoinDate'].fillna(method='ffill')

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\427651970.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['JoinDate'] = pd.to_datetime(df['JoinDate'], errors='coerce')
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\427651970.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['JoinDate'] = df['JoinDate'].fillna(method='ffill')
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\427651970.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['JoinDate'] = df['JoinDate'].fillna(method='ffill')

In [19]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576.0,2020-02-16,NaN,NaN,USA,NaN
1,David,20.0,Unknown,64288.0,2018-02-21,NaN,NaN,Canada,NaN
2,Bob,20.0,Unknown,39551.0,2019-04-17,NaN,NaN,NaN,NaN
3,Charlie,20.0,Female,57072.0,2021-04-08,NaN,NaN,India,Bad
4,Alice,20.0,Unknown,57072.0,2023-09-18,NaN,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850.0,2023-12-13,NaN,NaN,USA,Good
96,David,20.0,Male,98631.0,2020-12-15,Y,user26@mail.com,UK,Average
97,Bob,20.0,Female,57072.0,2023-05-18,Y,user14@mail.com,Canada,NaN
98,Eva,20.0,Male,57072.0,2021-11-05,NaN,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658.0,2021-11-05,0,NaN,India,Average

In [20]:
# 5. Clean Subscription column
df['Subscription'] = df['Subscription'].replace({
    'Y': 'Yes', 'N': 'No', '1': 'Yes', '0': 'No'
})
df['Subscription'] = df['Subscription'].fillna('No')

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\2025495984.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Subscription'] = df['Subscription'].replace({
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\2025495984.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Subscription'] = df['Subscription'].fillna('No')

In [21]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576.0,2020-02-16,No,NaN,USA,NaN
1,David,20.0,Unknown,64288.0,2018-02-21,No,NaN,Canada,NaN
2,Bob,20.0,Unknown,39551.0,2019-04-17,No,NaN,NaN,NaN
3,Charlie,20.0,Female,57072.0,2021-04-08,No,NaN,India,Bad
4,Alice,20.0,Unknown,57072.0,2023-09-18,No,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850.0,2023-12-13,No,NaN,USA,Good
96,David,20.0,Male,98631.0,2020-12-15,Yes,user26@mail.com,UK,Average
97,Bob,20.0,Female,57072.0,2023-05-18,Yes,user14@mail.com,Canada,NaN
98,Eva,20.0,Male,57072.0,2021-11-05,No,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658.0,2021-11-05,No,NaN,India,Average

In [22]:
# 6. Clean Email (fill with placeholder)
df['Email'] = df['Email'].fillna('unknown@example.com')

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\2604594510.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Email'] = df['Email'].fillna('unknown@example.com')

In [ ]:
# 6. Clean Email (fill with placeholder)
df['Email'] = df['Email'].fillna('unknown@example.com')

In [23]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576.0,2020-02-16,No,unknown@example.com,USA,NaN
1,David,20.0,Unknown,64288.0,2018-02-21,No,unknown@example.com,Canada,NaN
2,Bob,20.0,Unknown,39551.0,2019-04-17,No,unknown@example.com,NaN,NaN
3,Charlie,20.0,Female,57072.0,2021-04-08,No,unknown@example.com,India,Bad
4,Alice,20.0,Unknown,57072.0,2023-09-18,No,unknown@example.com,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850.0,2023-12-13,No,unknown@example.com,USA,Good
96,David,20.0,Male,98631.0,2020-12-15,Yes,user26@mail.com,UK,Average
97,Bob,20.0,Female,57072.0,2023-05-18,Yes,user14@mail.com,Canada,NaN
98,Eva,20.0,Male,57072.0,2021-11-05,No,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658.0,2021-11-05,No,unknown@example.com,India,Average

In [24]:
# 7. Clean Country
df['Country'] = df['Country'].replace('', np.nan)
df['Country'] = df['Country'].fillna('Unknown')

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1768248927.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].replace('', np.nan)
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\1768248927.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].fillna('Unknown')

In [28]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576.0,2020-02-16,No,unknown@example.com,USA,NaN
1,David,20.0,Unknown,64288.0,2018-02-21,No,unknown@example.com,Canada,NaN
2,Bob,20.0,Unknown,39551.0,2019-04-17,No,unknown@example.com,Unknown,NaN
3,Charlie,20.0,Female,57072.0,2021-04-08,No,unknown@example.com,India,Bad
4,Alice,20.0,Unknown,57072.0,2023-09-18,No,unknown@example.com,India,NaN
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850.0,2023-12-13,No,unknown@example.com,USA,Good
96,David,20.0,Male,98631.0,2020-12-15,Yes,user26@mail.com,UK,Average
97,Bob,20.0,Female,57072.0,2023-05-18,Yes,user14@mail.com,Canada,NaN
98,Eva,20.0,Male,57072.0,2021-11-05,No,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658.0,2021-11-05,No,unknown@example.com,India,Average

In [29]:
# 8. Clean Feedback (fill blanks or NaNs with 'No Feedback')
df['Feedback'] = df['Feedback'].replace('', np.nan)
df['Feedback'] = df['Feedback'].fillna('No Feedback')

C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\319534440.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Feedback'] = df['Feedback'].replace('', np.nan)
C:\Users\sakib\AppData\Local\Temp\ipykernel_12128\319534440.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Feedback'] = df['Feedback'].fillna('No Feedback')

In [30]:
df

,Name,Age,Gender,Income,JoinDate,Subscription,Email,Country,Feedback
0,David,20.0,Unknown,90576.0,2020-02-16,No,unknown@example.com,USA,No Feedback
1,David,20.0,Unknown,64288.0,2018-02-21,No,unknown@example.com,Canada,No Feedback
2,Bob,20.0,Unknown,39551.0,2019-04-17,No,unknown@example.com,Unknown,No Feedback
3,Charlie,20.0,Female,57072.0,2021-04-08,No,unknown@example.com,India,Bad
4,Alice,20.0,Unknown,57072.0,2023-09-18,No,unknown@example.com,India,No Feedback
...,...,...,...,...,...,...,...,...,...
95,Bob,37.0,Female,35850.0,2023-12-13,No,unknown@example.com,USA,Good
96,David,20.0,Male,98631.0,2020-12-15,Yes,user26@mail.com,UK,Average
97,Bob,20.0,Female,57072.0,2023-05-18,Yes,user14@mail.com,Canada,No Feedback
98,Eva,20.0,Male,57072.0,2021-11-05,No,user45@mail.com,UK,Good
99,Eva,57.0,Female,80658.0,2021-11-05,No,unknown@example.com,India,Average

In [31]:
# Save cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)